### PR TITLE
Update Template App BackupPC by Zabbix agent.xml

### PR DESCRIPTION
**Pull request by ma11011s**

### CODE REVIEW

**Comment by yurtesen** [comment]
Can you please explain why you are suggesting this change? What problem does it solve?

**Comment by dudeeka** [comment]
I test on Zabbix 6.2 this template, if i used without changes above, i got error on discovery like this:

Failed: SyntaxError: invalid json (at offset 2) at [anon] (duktape.c:36562) internal ...

After i replace preprocess regex started working.

**Comment by yurtesen** [comment]
@dudeeka I will try to test this change but can you explain your regex? how did you come up with?

**Comment by dedisoft** [comment]
Hi,
Using Zabbix 6.4, same issue solved with the patch from @dudeeka 
Thanks !

**Pull request merged**
